/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package create;

import implementDAO.concesionarios;
import implementDAO.conexionSQL;
import java.util.ArrayList;
import implementDAO.conductores;
import implementDAO.unidades;
import java.beans.PropertyVetoException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan_Garrido
 */
public class CreateUnidad extends javax.swing.JInternalFrame {

    private HashMap<String, List<String>> concesionariosF;
    private HashMap<String, String> conductoresF;

    public HashMap<String, List<String>> getConcesionariosF() {
        return concesionariosF;
    }

    public void setConcesionariosF(HashMap<String, List<String>> concesionariosF) {
        this.concesionariosF = concesionariosF;
    }

    public HashMap<String, String> getConductoresF() {
        return conductoresF;
    }

    public void setConductoresF(HashMap<String, String> conductoresF) {
        this.conductoresF = conductoresF;
    }
    public CreateUnidad() {
        initComponents();
        idCondu.setVisible(false);
        idCon.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numero = new javax.swing.JTextField();
        conceFiltro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        listaConce = new javax.swing.JComboBox<>();
        listaCon = new javax.swing.JComboBox<>();
        conFiltro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        placas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        iniSeg = new com.toedter.calendar.JDateChooser();
        finSeg = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        idCondu = new javax.swing.JTextField();
        idCon = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Unidad");

        conceFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conceFiltroKeyReleased(evt);
            }
        });

        jLabel1.setText("Conductor");

        jLabel2.setText("Concesionario");

        jLabel3.setText("Numero");

        listaConce.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaConceItemStateChanged(evt);
            }
        });

        listaCon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaConItemStateChanged(evt);
            }
        });

        conFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conFiltroKeyReleased(evt);
            }
        });

        jLabel4.setText("Placas");

        jLabel5.setText("Modelo");

        jLabel6.setText("Inicio Seguro");

        jLabel7.setText("Fin Seguro");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idCondu.setEditable(false);

        idCon.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iniSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(finSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel4)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(listaCon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idCondu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(conceFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(listaConce, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idCon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(conFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conceFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaConce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCondu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conFiltroKeyReleased
        listaCon.removeAllItems();
        String seleccion="", keyword;
        keyword = conFiltro.getText();
        conductoresF = conductores.buscaConductores(keyword);
        conductoresF.forEach((k,v) -> listaCon.addItem(k));
           /* for (int i = 0; i < conductoresF.size(); i++){
                    String item = conductoresF.get(i);
                    listaCon.addItem(item);
                    System.out.println("Item " + i + " : " + item);
             }*/
    }//GEN-LAST:event_conFiltroKeyReleased

    private void conceFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conceFiltroKeyReleased
        listaConce.removeAllItems();
        String seleccion="", keyword;
        keyword = conceFiltro.getText();
        concesionariosF = concesionarios.buscaConcesionarios(keyword);
        concesionariosF.forEach((k,v) -> listaConce.addItem(k));
        
    }//GEN-LAST:event_conceFiltroKeyReleased

    private void listaConItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaConItemStateChanged
       idCondu.setText(conductoresF.get(listaCon.getSelectedItem()));
       
    }//GEN-LAST:event_listaConItemStateChanged

    private void listaConceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaConceItemStateChanged
        idCon.setText(concesionariosF.get(listaConce.getSelectedItem()).get(0));
    }//GEN-LAST:event_listaConceItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean exec=false;
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        String dateIn = df.format(iniSeg.getDate());
        String dateFi = df.format(finSeg.getDate());
        if(idCon.getText().equals("") ||  idCondu.getText().equals("") ||  numero.getText().equals("") ||  dateIn.equals("") ||  dateFi.equals("") ||  modelo.getText().equals("")){
            JOptionPane.showMessageDialog (null, "Completa la información por favor", "Atención!!", JOptionPane.INFORMATION_MESSAGE);
 
        }else{
            exec= unidades.unidadInsert(Integer.parseInt(idCon.getText()), Integer.parseInt(idCondu.getText()), Integer.parseInt(numero.getText()),placas.getText(),dateIn,dateFi, modelo.getText());
            if(exec !=true){
                JOptionPane.showMessageDialog (null, "Parece que ha sucedido un problema", "Atención!!", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog (null, "Se ha agregado correctamente!", "", JOptionPane.INFORMATION_MESSAGE);
                try {
                    this.setClosed(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(CreateUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conFiltro;
    private javax.swing.JTextField conceFiltro;
    private com.toedter.calendar.JDateChooser finSeg;
    private javax.swing.JTextField idCon;
    private javax.swing.JTextField idCondu;
    private com.toedter.calendar.JDateChooser iniSeg;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> listaCon;
    private javax.swing.JComboBox<String> listaConce;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField placas;
    // End of variables declaration//GEN-END:variables
}
