/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package update;

import create.*;
import java.awt.Color;
import implementDAO.roles;
import implementDAO.users;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan_Garrido
 */
public class UpdateUser extends javax.swing.JInternalFrame {
    private static Map<Integer, String> rol = new HashMap<Integer, String>();
    HashMap<String, List<String>> usuario = new HashMap<>();
    List<String> lista = new ArrayList<String>();

    public List<String> getLista() {
        return lista;
    }

    public void setLista(List<String> lista) {
        this.lista = lista;
    }

    public HashMap<String, List<String>> getUsuario() {
        return usuario;
    }

    public void setUsuario(HashMap<String, List<String>> usuario) {
        this.usuario = usuario;
    }
    public UpdateUser() {
        initComponents();
        idRol.setVisible(false);
        idUser.setVisible(false);
        buscarRoles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avisoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        idRol = new javax.swing.JTextField();
        passText = new javax.swing.JPasswordField();
        pass2Text = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rolesBox = new javax.swing.JComboBox<>();
        usuarioText = new javax.swing.JTextField();
        correoText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idUser = new javax.swing.JTextField();
        usCombo = new javax.swing.JComboBox<>();
        filtro = new javax.swing.JTextField();
        checkPass = new javax.swing.JCheckBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Usuario");

        avisoLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        avisoLabel.setForeground(new java.awt.Color(204, 0, 0));

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idRol.setEditable(false);
        idRol.setFocusable(false);

        passText.setEnabled(false);

        pass2Text.setEnabled(false);

        jLabel1.setText("Rol");

        jLabel2.setText("Usuario");

        jLabel3.setText("Correo");

        jLabel4.setText("Password");

        jLabel5.setText("Repite Password");

        rolesBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rolesBoxItemStateChanged(evt);
            }
        });

        jLabel6.setText("Buscar");

        idUser.setEditable(false);

        usCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usComboActionPerformed(evt);
            }
        });

        filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroKeyReleased(evt);
            }
        });

        checkPass.setText("Editar");
        checkPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(rolesBox, 0, 107, Short.MAX_VALUE)
                                    .addComponent(filtro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(usuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(idRol, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(passText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(pass2Text, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(checkPass))
                            .addComponent(correoText, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(correoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkPass))
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pass2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean exec=false;
        if(correoText.getText().equals("")){
            avisoLabel.setForeground(Color.RED);
            avisoLabel.setText("Correo requerido");
        }else if(usuarioText.getText().equals("")){
            avisoLabel.setForeground(Color.RED);
            avisoLabel.setText("Usuario requerido");
        }else if(passText.getText().equals("")){
            avisoLabel.setForeground(Color.RED);
            avisoLabel.setText("Contraseña requerida");
        }
        else if(pass2Text.getText().equals("")){
            avisoLabel.setForeground(Color.RED);
            avisoLabel.setText("Las contraseñas no son iguales");
        }else if (verificaPass() != true){
            avisoLabel.setForeground(Color.RED);
            avisoLabel.setText("Revise los password");
        }else{
            exec=users.userInsert(usuarioText.getText(), correoText.getText(), passText.getText(), Integer.parseInt(idRol.getText()));
            // exec=true;
            if(exec!=true){
                JOptionPane.showMessageDialog (null, "Parece que ha sucedido un problema", "Atención!!", JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog (null, "Se ha agregado correctamente!", "", JOptionPane.INFORMATION_MESSAGE);
                try {
                    this.setClosed(true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(CreateUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rolesBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rolesBoxItemStateChanged
        idRol.setText((String) rolesBox.getSelectedItem());
        Iterator it = rol.keySet().iterator();
        while(it.hasNext()){
            Object key =  it.next();
            if(rol.get(key).equals(rolesBox.getSelectedItem())){
                idRol.setText(key.toString());
            }
        }
    }//GEN-LAST:event_rolesBoxItemStateChanged

    private void usComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usComboActionPerformed
        //usCombo.getSelectedItem().toString();
        Object obj = usCombo.getSelectedItem();
        if(obj != null){
            String sel= obj.toString();
            if(!sel.equals("Selecciona")){
                List<String> lista2 = new ArrayList<String>();
            lista2 = usuario.get(sel);
            usuarioText.setText(sel);
            correoText.setText(lista2.get(1));
            rolesBox.setSelectedItem(lista2.get(5));
            }
            else{
                usuarioText.setText("");
                correoText.setText("");
            }
            
        }
    }//GEN-LAST:event_usComboActionPerformed

    private void filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroKeyReleased
        if(!filtro.getText().equals("")){
            usCombo.removeAllItems();
            usuario = users.buscaUsuarios(filtro.getText());
            usCombo.addItem("Selecciona");
            usuario.forEach((k,v) -> usCombo.addItem(k));
        }
        else{
            usCombo.removeAllItems();
            usuario.clear();
            lista.clear();
        }
    }//GEN-LAST:event_filtroKeyReleased

    private void checkPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPassActionPerformed
            if(checkPass.isSelected()){
                passText.setEnabled(true);
                pass2Text.setEnabled(true);
            }else{
                passText.setEnabled(false);
                pass2Text.setEnabled(false);
                passText.setText("");
                pass2Text.setText("");
            }
            
    }//GEN-LAST:event_checkPassActionPerformed
    private void buscarRoles(){
        rol = roles.getRoles();
        Iterator it = rol.keySet().iterator();
        while(it.hasNext()){
          Object key =  it.next();
          rolesBox.addItem(rol.get(key));
          System.out.println("Clave: " + key + " -> Valor: " + rol.get(key));
     }
    }
    private boolean verificaPass(){
        boolean choice = false; 
        if(!pass2Text.getText().equals("")){
            if(!passText.getText().equals(pass2Text.getText())){  
                choice = false;
            }
            else{
                choice = true;
            }
        }
        return choice;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JCheckBox checkPass;
    private javax.swing.JTextField correoText;
    private javax.swing.JTextField filtro;
    private javax.swing.JTextField idRol;
    private javax.swing.JTextField idUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pass2Text;
    private javax.swing.JPasswordField passText;
    private javax.swing.JComboBox<String> rolesBox;
    private javax.swing.JComboBox<String> usCombo;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
