/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package limo;

import create.*;
import delete.*;
import update.*;
import view.*;
import extra.*;


/**
 *
 * @author Juan_Garrido
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Nuevo = new javax.swing.JMenu();
        createUser = new javax.swing.JMenuItem();
        createConductor = new javax.swing.JMenuItem();
        createConcesionario = new javax.swing.JMenuItem();
        createUnidad = new javax.swing.JMenuItem();
        createConductor1 = new javax.swing.JMenuItem();
        createConductor2 = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        updateUser = new javax.swing.JMenuItem();
        updateConductor = new javax.swing.JMenuItem();
        updateConsecionario = new javax.swing.JMenuItem();
        updateUnidad = new javax.swing.JMenuItem();
        createConductor3 = new javax.swing.JMenuItem();
        createConductor4 = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenu();
        deleteUser = new javax.swing.JMenuItem();
        deleteConductor = new javax.swing.JMenuItem();
        deleteConsecionario = new javax.swing.JMenuItem();
        deleteUnidad = new javax.swing.JMenuItem();
        createConductor5 = new javax.swing.JMenuItem();
        createConductor6 = new javax.swing.JMenuItem();
        Borrar1 = new javax.swing.JMenu();
        viewUsers = new javax.swing.JMenuItem();
        deleteConductor1 = new javax.swing.JMenuItem();
        deleteConsecionario1 = new javax.swing.JMenuItem();
        deleteUnidad1 = new javax.swing.JMenuItem();
        Borrar2 = new javax.swing.JMenu();
        viewUsers1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        Nuevo.setText("Nuevo");

        createUser.setText("Usuario");
        createUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserActionPerformed(evt);
            }
        });
        Nuevo.add(createUser);

        createConductor.setText("Conductor");
        createConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductorActionPerformed(evt);
            }
        });
        Nuevo.add(createConductor);

        createConcesionario.setText("Concesionario");
        createConcesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConcesionarioActionPerformed(evt);
            }
        });
        Nuevo.add(createConcesionario);

        createUnidad.setText("Unidad");
        createUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUnidadActionPerformed(evt);
            }
        });
        Nuevo.add(createUnidad);

        createConductor1.setText("Local");
        createConductor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductor1ActionPerformed(evt);
            }
        });
        Nuevo.add(createConductor1);

        createConductor2.setText("Foranea");
        createConductor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductor2ActionPerformed(evt);
            }
        });
        Nuevo.add(createConductor2);

        jMenuBar1.add(Nuevo);

        Editar.setText("Editar");

        updateUser.setText("Usuario");
        updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserActionPerformed(evt);
            }
        });
        Editar.add(updateUser);

        updateConductor.setText("Conductor");
        updateConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateConductorActionPerformed(evt);
            }
        });
        Editar.add(updateConductor);

        updateConsecionario.setText("Concesionario");
        updateConsecionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateConsecionarioActionPerformed(evt);
            }
        });
        Editar.add(updateConsecionario);

        updateUnidad.setText("Unidad");
        updateUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUnidadActionPerformed(evt);
            }
        });
        Editar.add(updateUnidad);

        createConductor3.setText("Foranea");
        createConductor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductor3ActionPerformed(evt);
            }
        });
        Editar.add(createConductor3);

        createConductor4.setText("Local");
        createConductor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductor4ActionPerformed(evt);
            }
        });
        Editar.add(createConductor4);

        jMenuBar1.add(Editar);

        Borrar.setText("Borrar");

        deleteUser.setText("Usuario");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });
        Borrar.add(deleteUser);

        deleteConductor.setText("Conductor");
        deleteConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConductorActionPerformed(evt);
            }
        });
        Borrar.add(deleteConductor);

        deleteConsecionario.setText("Concesionario");
        deleteConsecionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConsecionarioActionPerformed(evt);
            }
        });
        Borrar.add(deleteConsecionario);

        deleteUnidad.setText("Unidad");
        deleteUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUnidadActionPerformed(evt);
            }
        });
        Borrar.add(deleteUnidad);

        createConductor5.setText("Foranea");
        createConductor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductor5ActionPerformed(evt);
            }
        });
        Borrar.add(createConductor5);

        createConductor6.setText("Local");
        createConductor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConductor6ActionPerformed(evt);
            }
        });
        Borrar.add(createConductor6);

        jMenuBar1.add(Borrar);

        Borrar1.setText("Ver");

        viewUsers.setText("Usuarios");
        viewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersActionPerformed(evt);
            }
        });
        Borrar1.add(viewUsers);

        deleteConductor1.setText("Conductores");
        deleteConductor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConductor1ActionPerformed(evt);
            }
        });
        Borrar1.add(deleteConductor1);

        deleteConsecionario1.setText("Concesionarios");
        deleteConsecionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteConsecionario1ActionPerformed(evt);
            }
        });
        Borrar1.add(deleteConsecionario1);

        deleteUnidad1.setText("Unidades");
        deleteUnidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUnidad1ActionPerformed(evt);
            }
        });
        Borrar1.add(deleteUnidad1);

        jMenuBar1.add(Borrar1);

        Borrar2.setText("Extra");

        viewUsers1.setText("Código de Barras");
        viewUsers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsers1ActionPerformed(evt);
            }
        });
        Borrar2.add(viewUsers1);

        jMenuBar1.add(Borrar2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserActionPerformed
           CreateUser newUser = new CreateUser(); 
           desktop.add(newUser);
           newUser.show();
    }//GEN-LAST:event_createUserActionPerformed

    private void createConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductorActionPerformed
           CreateConductor newConductor = new CreateConductor(); 
           desktop.add(newConductor);
           newConductor.show();
    }//GEN-LAST:event_createConductorActionPerformed

    private void createConcesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConcesionarioActionPerformed
           CreateConcesionario newConcesionario = new CreateConcesionario(); 
           desktop.add(newConcesionario);
           newConcesionario.show();
    }//GEN-LAST:event_createConcesionarioActionPerformed

    private void createUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUnidadActionPerformed
           CreateUnidad newUnidad = new CreateUnidad(); 
           desktop.add(newUnidad);
           newUnidad.show();
    }//GEN-LAST:event_createUnidadActionPerformed

    private void updateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserActionPerformed
           UpdateUser upUser = new UpdateUser(); 
           desktop.add(upUser);
           upUser.show();
    }//GEN-LAST:event_updateUserActionPerformed

    private void updateConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateConductorActionPerformed
           UpdateConductor upConductor = new UpdateConductor(); 
           desktop.add(upConductor);
           upConductor.show();
    }//GEN-LAST:event_updateConductorActionPerformed

    private void updateConsecionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateConsecionarioActionPerformed
           UpdateConcesionario upConcesionario = new UpdateConcesionario(); 
           desktop.add(upConcesionario);
           upConcesionario.show();
    }//GEN-LAST:event_updateConsecionarioActionPerformed

    private void updateUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUnidadActionPerformed
           UpdateUnidad upUnidad = new UpdateUnidad(); 
           desktop.add(upUnidad);
           upUnidad.show();
    }//GEN-LAST:event_updateUnidadActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
           DeleteUser delUser = new DeleteUser(); 
           desktop.add(delUser);
           delUser.show();
    }//GEN-LAST:event_deleteUserActionPerformed

    private void deleteConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConductorActionPerformed
           DeleteConductor delConductor = new DeleteConductor(); 
           desktop.add(delConductor);
           delConductor.show();
    }//GEN-LAST:event_deleteConductorActionPerformed

    private void deleteConsecionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConsecionarioActionPerformed
           DeleteConcesionario delConcesionario = new DeleteConcesionario(); 
           desktop.add(delConcesionario);
           delConcesionario.show();
    }//GEN-LAST:event_deleteConsecionarioActionPerformed

    private void deleteUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUnidadActionPerformed
           DeleteUnidad delUnidad = new DeleteUnidad(); 
           desktop.add(delUnidad);
           delUnidad.show();
    }//GEN-LAST:event_deleteUnidadActionPerformed

    private void viewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersActionPerformed
       viewUsers viewUser = new viewUsers(); 
           desktop.add(viewUser);
           viewUser.show();
    }//GEN-LAST:event_viewUsersActionPerformed

    private void deleteConductor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConductor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteConductor1ActionPerformed

    private void deleteConsecionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteConsecionario1ActionPerformed
        viewConcesionarios viewCon = new viewConcesionarios(); 
           desktop.add(viewCon);
           viewCon.show();
    }//GEN-LAST:event_deleteConsecionario1ActionPerformed

    private void deleteUnidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUnidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUnidad1ActionPerformed

    private void viewUsers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsers1ActionPerformed
       CodigoBarras viewCodigo = new CodigoBarras(); 
           desktop.add(viewCodigo);
           viewCodigo.show();
    }//GEN-LAST:event_viewUsers1ActionPerformed

    private void createConductor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductor1ActionPerformed
      CreateLocal local = new CreateLocal();
      desktop.add(local);
      local.show();
    }//GEN-LAST:event_createConductor1ActionPerformed

    private void createConductor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductor2ActionPerformed
       CreateForanea foranea = new CreateForanea();
       desktop.add(foranea);
       foranea.show();
    }//GEN-LAST:event_createConductor2ActionPerformed

    private void createConductor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createConductor3ActionPerformed

    private void createConductor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createConductor4ActionPerformed

    private void createConductor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductor5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createConductor5ActionPerformed

    private void createConductor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConductor6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createConductor6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Borrar;
    private javax.swing.JMenu Borrar1;
    private javax.swing.JMenu Borrar2;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenu Nuevo;
    private javax.swing.JMenuItem createConcesionario;
    private javax.swing.JMenuItem createConductor;
    private javax.swing.JMenuItem createConductor1;
    private javax.swing.JMenuItem createConductor2;
    private javax.swing.JMenuItem createConductor3;
    private javax.swing.JMenuItem createConductor4;
    private javax.swing.JMenuItem createConductor5;
    private javax.swing.JMenuItem createConductor6;
    private javax.swing.JMenuItem createUnidad;
    private javax.swing.JMenuItem createUser;
    private javax.swing.JMenuItem deleteConductor;
    private javax.swing.JMenuItem deleteConductor1;
    private javax.swing.JMenuItem deleteConsecionario;
    private javax.swing.JMenuItem deleteConsecionario1;
    private javax.swing.JMenuItem deleteUnidad;
    private javax.swing.JMenuItem deleteUnidad1;
    private javax.swing.JMenuItem deleteUser;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem updateConductor;
    private javax.swing.JMenuItem updateConsecionario;
    private javax.swing.JMenuItem updateUnidad;
    private javax.swing.JMenuItem updateUser;
    private javax.swing.JMenuItem viewUsers;
    private javax.swing.JMenuItem viewUsers1;
    // End of variables declaration//GEN-END:variables
}
